// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: todo.sql

package db

import (
	"context"
	"time"
)

const assignUserToTodo = `-- name: AssignUserToTodo :execrows
INSERT INTO todo_user (todo_id, user_id)
VALUES ($1, $2)
`

type AssignUserToTodoParams struct {
	TodoID int32 `json:"todo_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) AssignUserToTodo(ctx context.Context, arg AssignUserToTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignUserToTodo, arg.TodoID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todo (title, description, creator_id)
VALUES ($1, $2, $3)
RETURNING id, creator_id, title, description, completed, created_at, updated_at
`

type CreateTodoParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatorID   int32  `json:"creator_id"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Title, arg.Description, arg.CreatorID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :execrows
DELETE FROM todo
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTodo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTodosOfUser = `-- name: GetTodosOfUser :many
SELECT id, creator_id, title, description, completed, created_at, updated_at, todo_id, user_id FROM todo
JOIN todo_user ON todo.id = todo_user.todo_id
WHERE todo_user.user_id = $1
`

type GetTodosOfUserRow struct {
	ID          int32     `json:"id"`
	CreatorID   int32     `json:"creator_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Completed   bool      `json:"completed"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	TodoID      int32     `json:"todo_id"`
	UserID      int32     `json:"user_id"`
}

func (q *Queries) GetTodosOfUser(ctx context.Context, userID int32) ([]GetTodosOfUserRow, error) {
	rows, err := q.db.Query(ctx, getTodosOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTodosOfUserRow{}
	for rows.Next() {
		var i GetTodosOfUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TodoID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todo
SET title = $1, description = $2, completed = $3
WHERE id = $4
RETURNING id, creator_id, title, description, completed, created_at, updated_at
`

type UpdateTodoParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Completed   bool   `json:"completed"`
	ID          int32  `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
